keys:
  - &jokyv age1ztfa88hexsumqz9vjpmfmxzg5crhrjrpy49hlkk02suqmd8a34uqw6mpmk
creation_rules:
  - path_regex: secrets(\.enc)?\.yaml$
    # - path: secrets.enc.yaml
    key_groups:
      - age:
          - *jokyv
