keys:
  - &jokyv age1rh0g0hqwkdrf2ev6hw62ltywfeh8tlr5wpdrqany8mzgf6prgp3qyedk63

creation_rules:
  - path_regex: secrets(\.enc)?\.yaml$
  # - path: secrets.enc.yaml
    key_groups:
    - age:
      - *jokyv
