[nixpkgs]
packages = [
  "aider-chat",
  "firefox",
  "helix",
  "python313",
  "foot",
  "yazi",
  "zoxide",
]

[home-manager]
packages = [
  "home-manager",
]

[stylix]
packages = [
  "stylix",
]

[niri]
packages = [
  "niri",
]
