# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernel.sysctl = {
    "vm.swappiness" = 10;
  };
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/80fb4361-f167-4ef1-8701-56aa4a0d5e36";
    fsType = "btrfs";
    options = [ "subvol=@" "noatime" "compress-force=zstd:3" "ssd" "discard=async" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/80fb4361-f167-4ef1-8701-56aa4a0d5e36";
    fsType = "btrfs";
    options = [ "subvol=@home" "noatime" "compress=zstd" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/80fb4361-f167-4ef1-8701-56aa4a0d5e36";
    fsType = "btrfs";
    options = [ "subvol=@nix" "noatime" "compress-force=zstd:1" "nodatacow" ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/80fb4361-f167-4ef1-8701-56aa4a0d5e36";
    fsType = "btrfs";
    options = [ "subvol=@var" "noatime" "compress=zstd" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8EC2-84E6";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # Add tmpfs for /tmp
  fileSystems."/tmp" = {
    fsType = "tmpfs";
    options = [ "defaults" "size=4G" "mode=1777" ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/1f123baf-812e-4b34-8caf-9c1734bf26d6";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
